services:
  - type: web
    name: anime-embed-hunter
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_DEBUG
        value: "false"
      - key: DATABASE_URL
        value: "INSIRA_URL_DO_SUPABASE_AQUI"
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        value: "6767"
      - key: HEADLESS
        value: "true"
      - key: BROWSER_TIMEOUT
        value: "60000"
