"""Add latest_episode_info and episode_info fields

Revision ID: 64eb3ba48bbb
Revises: 7e0f0d889538
Create Date: 2026-05-06 17:00:17.992666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eb3ba48bbb'
down_revision = '7e0f0d889538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_episode_info', sa.String(length=100), nullable=True))

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=100), nullable=True))
        batch_op.create_index('idx_episodes_anime_id', ['anime_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index('idx_episodes_anime_id')
        batch_op.drop_column('info')

    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.drop_column('latest_episode_info')

    # ### end Alembic commands ###
