"""Add cover_url to animes

Revision ID: 7e0f0d889538
Revises: 9a2bbd8c1320
Create Date: 2026-05-05 04:37:23.949911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0f0d889538'
down_revision = '9a2bbd8c1320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))
        batch_op.drop_constraint(batch_op.f('animes_url_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_animes_name_trgm'), postgresql_using='gin')

    with op.batch_alter_table('embed_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('embed_requests_url_key'), type_='unique')

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('episodes_url_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_episodes_anime_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_anime_id'), ['anime_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('episodes_url_key'), ['url'])

    with op.batch_alter_table('embed_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('embed_requests_url_key'), ['url'])

    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animes_name_trgm'), ['name'], unique=False, postgresql_using='gin')
        batch_op.create_unique_constraint(batch_op.f('animes_url_key'), ['url'])
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
